# unbind defaults
unbind C-b
unbind %

# bind to C-a (screen like)
set -g prefix C-a

# last window
bind a last-window

# choose window (bufexplorer like)
bind b choose-window

# use vim motion keys while in copy mode
setw -g mode-keys vi

# use "v" and "s" to do vertical/horizontal splits, like vim
bind s split-window -v
bind v split-window -h

# use the vim motion keys to move between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resizing shortcut
bind - resize-pane -D 10
bind = resize-pane -U 15
bind < resize-pane -L 10
bind > resize-pane -R 20

# set status bar
set -g status-style bg=colour235,fg=colour246,default
set -g status-left '#[fg=colour246] # #[fg=default]'
set -g status-right '#[fg=colour246] %d/%m/%Y %H:%M # #[fg=default]'

# highlight active window
setw -g window-status-style fg=colour246
setw -g window-status-format " #I. #W "
setw -g window-status-current-style bg=colour234,fg=colour190
setw -g window-status-current-format " #I: #W "

# message appearance
set -g message-style bg=colour234,fg=colour184

# pane appearance
set -g pane-active-border-style fg=colour190
set -g pane-border-style fg=colour240

# start numbering from 1
set -g base-index 1

# faster command sequences
set -s escape-time 0

# scrollback buffer size
set -g history-limit 10000

# don't automatically set window title
setw -g automatic-rename off

# 256 colors
set -g default-terminal 'screen-256color'

# status position
set -g status-position bottom

